src/ActiveMQ.Net/IProducer.cs, src/ActiveMQ.Net/Producer.cs, test/ActiveMQ.Net.Tests/ProducerProduceMessageSpec.cs, test/ActiveMQ.Net.Tests/Utils/MessageProcessor.cs, test/ActiveMQ.Net.Tests/Utils/TestContainerHost.cs
=> Fire and forget produce

src/ActiveMQ.Net/Consumer.cs, src/ActiveMQ.Net/IConsumer.cs, test/ActiveMQ.Net.Tests/ConsumerMessageAcknowledgementSpec.cs, test/ActiveMQ.Net.Tests/Utils/MessageSource.cs
=> Message acknowledgement

src/ActiveMQ.Net/ActiveMQ.Net.csproj, src/ActiveMQ.Net/ConnectionFactory.cs, test/ActiveMQ.Net.Tests/ActiveMQNetSpec.cs, test/ActiveMQ.Net.Tests/ConnectionSpec.cs, test/ActiveMQ.Net.Tests/ConsumerConsumeMessageSpec.cs, test/ActiveMQ.Net.Tests/ConsumerMessageAcknowledgementSpec.cs, test/ActiveMQ.Net.Tests/CreateConsumerSpec.cs, test/ActiveMQ.Net.Tests/CreateProducerSpec.cs, test/ActiveMQ.Net.Tests/Logging/TestLogger.cs, test/ActiveMQ.Net.Tests/Logging/TestLoggerFactory.cs, test/ActiveMQ.Net.Tests/ProducerProduceMessageSpec.cs
=> Add support for logging with logging.abstractions

src/ActiveMQ.Net/Connection.cs, src/ActiveMQ.Net/ConnectionExtensions.cs, src/ActiveMQ.Net/CreateProducerException.cs, src/ActiveMQ.Net/IConnection.cs, src/ActiveMQ.Net/ProducerBuilder.cs, test/ActiveMQ.Net.Tests/CreateProducerSpec.cs, test/ActiveMQ.Net.Tests/ProducerProduceMessageSpec.cs
=> Create Producer asynchronously

src/ActiveMQ.Net/IProducer.cs, src/ActiveMQ.Net/MessageOutcomes.cs, src/ActiveMQ.Net/MessageSendException.cs, src/ActiveMQ.Net/Producer.cs, test/ActiveMQ.Net.Tests/ProducerProduceMessageSpec.cs
=> Implement cancellable ProduceAsync

src/ActiveMQ.Net/ActiveMQ.Net.csproj
=> Target .NET Standard 2.0

src/ActiveMQ.Net/ActiveMQ.Net.csproj, src/ActiveMQ.Net/AutoRecovering/AutoRecoveringConnection.cs, src/ActiveMQ.Net/AutoRecovering/AutoRecoveringConsumer.cs, src/ActiveMQ.Net/AutoRecovering/AutoRecoveringProducer.cs, src/ActiveMQ.Net/AutoRecovering/IRecoverable.cs
=> Use signaling to invoke pending send operations when Producer recovered

src/ActiveMQ.Net/AutoRecovering/AutoRecoveringConsumer.cs
=> Use signaling to invoke pending receive operations when Consumer recovered

src/ActiveMQ.Net/AutoRecovering/AutoRecoveringConnection.cs, test/ActiveMQ.Net.Tests/ActiveMQ.Net.Tests.csproj, test/ActiveMQ.Net.Tests/AutoRecovering/AutoRecoveringConnectionSpec.cs, test/ActiveMQ.Net.Tests/AutoRecovering/AutoRecoveringConsumerSpec.cs, test/ActiveMQ.Net.Tests/AutoRecovering/AutoRecoveringProducerSpec.cs, test/ActiveMQ.Net.Tests/Utils/DisposeUtil.cs, test/ActiveMQ.Net.Tests/xunit.runner.json
=> Fix tests on ci env

src/ActiveMQ.Net/AutoRecovering/AutoRecoveringConnection.cs, src/ActiveMQ.Net/AutoRecovering/AutoRecoveringConsumer.cs, src/ActiveMQ.Net/AutoRecovering/AutoRecoveringProducer.cs, src/ActiveMQ.Net/AutoRecovering/IRecoverable.cs, src/ActiveMQ.Net/Connection.cs, src/ActiveMQ.Net/ConnectionClosedEventArgs.cs, src/ActiveMQ.Net/IConnection.cs, src/ActiveMQ.Net/Producer.cs, src/ActiveMQ.Net/ProducerBuilder.cs, test/ActiveMQ.Net.Tests/ActiveMQNetSpec.cs, test/ActiveMQ.Net.Tests/AutoRecovering/AutoRecoveringProducerSpec.cs
=> Rework link recovery

src/ActiveMQ.Net/AutoRecovering/AutoRecoveringConsumer.cs, src/ActiveMQ.Net/Connection.cs, src/ActiveMQ.Net/Consumer.cs, src/ActiveMQ.Net/ConsumerBuilder.cs, src/ActiveMQ.Net/Producer.cs, src/ActiveMQ.Net/ProducerClosedException.cs, test/ActiveMQ.Net.Tests/AutoRecovering/AutoRecoveringConsumerSpec.cs, test/ActiveMQ.Net.Tests/AutoRecovering/AutoRecoveringProducerSpec.cs
=> Fix failing tests on CI

src/ActiveMQ.Net/AutoRecovering/AutoRecoveringConnection.cs, src/ActiveMQ.Net/Builders/ConnectionBuilder.cs, src/ActiveMQ.Net/Builders/ConsumerBuilder.cs, src/ActiveMQ.Net/Builders/ProducerBuilder.cs, src/ActiveMQ.Net/Connection.cs, src/ActiveMQ.Net/ConnectionFactory.cs, test/ActiveMQ.Net.Tests/ActiveMQNetSpec.cs, test/ActiveMQ.Net.Tests/ConnectionFactorySpec.cs
=> Optional connection auto recovering

src/ActiveMQ.Net/AutoRecovering/AutoRecoveringConnection.cs, src/ActiveMQ.Net/AutoRecovering/AutoRecoveringConsumer.cs, src/ActiveMQ.Net/AutoRecovering/AutoRecoveringProducer.cs, src/ActiveMQ.Net/AutoRecovering/IRecoverable.cs, src/ActiveMQ.Net/Builders/ConsumerBuilder.cs, src/ActiveMQ.Net/Connection.cs, src/ActiveMQ.Net/ConnectionExtensions.cs, src/ActiveMQ.Net/IConnection.cs, test/ActiveMQ.Net.Tests/CreateConsumerSpec.cs, test/ActiveMQ.Net.Tests/Utils/TestContainerHost.cs, test/ActiveMQ.Net.Tests/Utils/TestLinkProcessor.cs
=> Cancellable CreateConsumerAsync

src/ActiveMQ.Net/AutoRecovering/AutoRecoveringConnection.cs, src/ActiveMQ.Net/AutoRecovering/AutoRecoveringProducer.cs, src/ActiveMQ.Net/Builders/ProducerBuilder.cs, src/ActiveMQ.Net/Connection.cs, src/ActiveMQ.Net/ConnectionExtensions.cs, src/ActiveMQ.Net/IConnection.cs, test/ActiveMQ.Net.Tests/ActiveMQNetSpec.cs, test/ActiveMQ.Net.Tests/CreateConsumerSpec.cs, test/ActiveMQ.Net.Tests/CreateProducerSpec.cs
=> Cancellable CreateProducerAsync

src/ActiveMQ.Net/ActiveMQ.Net.csproj, src/ActiveMQ.Net/AutoRecovering/AutoRecoveringConnection.cs, src/ActiveMQ.Net/AutoRecovering/AutoRecoveringProducer.cs, src/ActiveMQ.Net/Builders/ConsumerBuilder.cs, src/ActiveMQ.Net/Builders/ProducerBuilder.cs, src/ActiveMQ.Net/ConnectionFactory.cs, src/ActiveMQ.Net/Endpoint.cs, src/ActiveMQ.Net/Exceptions/CreateConnectionException.cs, src/ActiveMQ.Net/Exceptions/CreateConsumerException.cs, src/ActiveMQ.Net/Exceptions/CreateEndpointException.cs, src/ActiveMQ.Net/Exceptions/CreateProducerException.cs, src/ActiveMQ.Net/Exceptions/MessageSendException.cs, src/ActiveMQ.Net/Exceptions/ProducerClosedException.cs, src/ActiveMQ.Net/PollyContextExtensions.cs, src/ActiveMQ.Net/Producer.cs, test/ActiveMQ.Net.Tests/ActiveMQNetSpec.cs, test/ActiveMQ.Net.Tests/AutoRecovering/AutoRecoveringConnectionSpec.cs, test/ActiveMQ.Net.Tests/ConnectionFactorySpec.cs, test/ActiveMQ.Net.Tests/CreateConsumerSpec.cs, test/ActiveMQ.Net.Tests/EndpointSpec.cs, test/ActiveMQ.Net.Tests/ProducerSendMessageSpec.cs, test/ActiveMQ.Net.Tests/Utils/MessageProcessor.cs, test/ActiveMQ.Net.Tests/Utils/TestContainerHost.cs
=> Create connection with a list of endpoints

src/ActiveMQ.Net/AutoRecovering/AutoRecoveringConnection.cs, src/ActiveMQ.Net/Builders/ConnectionBuilder.cs, src/ActiveMQ.Net/ConnectionFactory.cs, src/ActiveMQ.Net/ConnectionFactoryExtensions.cs, src/ActiveMQ.Net/Exceptions/CreateConnectionException.cs, test/ActiveMQ.Net.Tests/ConnectionFactorySpec.cs
=> Create cancellable connection

src/ActiveMQ.Net/ApplicationProperties.cs, src/ActiveMQ.Net/Message.cs, test/ActiveMQ.Net.Tests/MessageSpec.cs, test/ActiveMQ.Net.Tests/Utils/MessageProcessor.cs, test/ActiveMQ.Net.Tests/Utils/TestContainerHost.cs
=> Support Application Properties

src/ActiveMQ.Net/AutoRecovering/AutoRecoveringConnection.cs, src/ActiveMQ.Net/Builders/ConnectionBuilder.cs, src/ActiveMQ.Net/Connection.cs, src/ActiveMQ.Net/ConnectionRecoveredEventArgs.cs, src/ActiveMQ.Net/IConnection.cs, test/ActiveMQ.Net.Tests/AutoRecovering/AutoRecoveringConnectionSpec.cs
=> Raise ConnectionRecovered event when connection recovered

ActiveMQ.Net.sln.DotSettings, src/ActiveMQ.Net/AutoRecovering/AutoRecoveringConnection.cs, src/ActiveMQ.Net/AutoRecovering/RecoveryPolicy/ConstantBackoffRecoveryPolicy.cs, src/ActiveMQ.Net/AutoRecovering/RecoveryPolicy/ExponentialBackoffRecoveryPolicy.cs, src/ActiveMQ.Net/AutoRecovering/RecoveryPolicy/IRecoveryPolicy.cs, src/ActiveMQ.Net/AutoRecovering/RecoveryPolicy/LinearBackoffRecoveryPolicy.cs, src/ActiveMQ.Net/AutoRecovering/RecoveryPolicy/RecoveryPolicyConsts.cs, src/ActiveMQ.Net/AutoRecovering/RecoveryPolicy/RecoveryPolicyFactory.cs, src/ActiveMQ.Net/ConnectionFactory.cs, src/ActiveMQ.Net/PollyContextExtensions.cs, test/ActiveMQ.Net.Tests/AutoRecovering/RecoveryPolicy/ConstantBackoffRecoveryPolicySpec.cs, test/ActiveMQ.Net.Tests/AutoRecovering/RecoveryPolicy/ExponentialBackoffRecoveryPolicySpec.cs, test/ActiveMQ.Net.Tests/AutoRecovering/RecoveryPolicy/LinearBackoffRecoveryPolicySpec.cs, test/ActiveMQ.Net.Tests/AutoRecovering/RecoveryPolicy/RecoveryPolicyUtils.cs, test/ActiveMQ.Net.Tests/ConnectionFactorySpec.cs
=> Configurable recovery policy

src/ActiveMQ.Net/ActiveMQ.Net.csproj, test/ActiveMQ.Net.Tests/Utils/TestContainerHost.cs
=> Update AMQPNetLite to 2.4.0

src/ActiveMQ.Net/AutoRecovering/AutoRecoveringConnection.cs, src/ActiveMQ.Net/AutoRecovering/AutoRecoveringConsumer.cs, src/ActiveMQ.Net/AutoRecovering/AutoRecoveringProducer.cs, src/ActiveMQ.Net/Builders/ConsumerBuilder.cs, src/ActiveMQ.Net/Builders/ProducerBuilder.cs, src/ActiveMQ.Net/Connection.cs, src/ActiveMQ.Net/ConnectionExtensions.cs, src/ActiveMQ.Net/ConsumerConfiguration.cs, src/ActiveMQ.Net/IConnection.cs, src/ActiveMQ.Net/Message.cs, src/ActiveMQ.Net/MessageAnnotations.cs, src/ActiveMQ.Net/Producer.cs, src/ActiveMQ.Net/ProducerConfiguration.cs, src/ActiveMQ.Net/Properties.cs, src/ActiveMQ.Net/RoutingTypeExtensions.cs, src/ActiveMQ.Net/SymbolUtils.cs, test/ActiveMQ.Net.Tests/ProducerSendMessageSpec.cs
=> Configurable sender routing 

src/ActiveMQ.Net/AddressRoutingType.cs, src/ActiveMQ.Net/AnonymousProducer.cs, src/ActiveMQ.Net/AutoRecovering/AutoRecoveringAnonymousProducer.cs, src/ActiveMQ.Net/AutoRecovering/AutoRecoveringConnection.cs, src/ActiveMQ.Net/AutoRecovering/AutoRecoveringProducerBase.cs, src/ActiveMQ.Net/Builders/AnonymousProducerBuilder.cs, src/ActiveMQ.Net/Connection.cs, src/ActiveMQ.Net/ConnectionExtensions.cs, src/ActiveMQ.Net/ConsumerConfiguration.cs, src/ActiveMQ.Net/IAnonymousProducer.cs, src/ActiveMQ.Net/IConnection.cs, src/ActiveMQ.Net/Producer.cs, src/ActiveMQ.Net/ProducerBase.cs, src/ActiveMQ.Net/ProducerConfiguration.cs, src/ActiveMQ.Net/Properties.cs, src/ActiveMQ.Net/QueueRoutingType.cs, src/ActiveMQ.Net/RoutingTypeExtensions.cs, test/ActiveMQ.Net.Tests/AutoRecovering/AutoRecoveringConnectionSpec.cs, test/ActiveMQ.Net.Tests/AutoRecovering/AutoRecoveringConsumerSpec.cs, test/ActiveMQ.Net.Tests/AutoRecovering/AutoRecoveringProducerSpec.cs, test/ActiveMQ.Net.Tests/ConsumerMessageAcknowledgementSpec.cs, test/ActiveMQ.Net.Tests/ConsumerReceiveMessageSpec.cs, test/ActiveMQ.Net.Tests/CreateConsumerSpec.cs, test/ActiveMQ.Net.Tests/CreateProducerSpec.cs, test/ActiveMQ.Net.Tests/MessageSpec.cs, test/ActiveMQ.Net.Tests/ProducerSendMessageSpec.cs, test/ActiveMQ.Net.Tests/Utils/TestLinkProcessor.cs
=> Introduce Anonymous Producer

src/ActiveMQ.Net/Builders/ConnectionBuilder.cs, src/ActiveMQ.Net/Builders/SessionBuilder.cs, src/ActiveMQ.Net/Connection.cs, src/ActiveMQ.Net/Exceptions/CreateSessionException.cs, test/ActiveMQ.Net.Tests/ConnectionSpec.cs, test/ActiveMQ.Net.Tests/Utils/TestHandler.cs
=> Create session per Producer or Consumer link

src/ActiveMQ.Net/AutoRecovering/AutoRecoveringAnonymousProducer.cs, src/ActiveMQ.Net/AutoRecovering/AutoRecoveringConsumer.cs, src/ActiveMQ.Net/AutoRecovering/AutoRecoveringProducer.cs, src/ActiveMQ.Net/AutoRecovering/AutoRecoveringProducerBase.cs
Additionally some logging cleanup. 
It closes #78.
=> Rework auto recovering classes not to use recursion for retries

test/ActiveMQ.Net.IntegrationTests/AnonymousMessageProducerSpec.cs
=> Test Anonymous Message Producer

src/ActiveMQ.Net/Builders/ConsumerBuilder.cs, src/ActiveMQ.Net/Consumer.cs, src/ActiveMQ.Net/ConsumerConfiguration.cs, test/ActiveMQ.Net.IntegrationTests/ConsumerCreditSpec.cs, test/ActiveMQ.Net.UnitTests/CreateConsumerSpec.cs
=> Configurable consumer credit

README.md
=> Sending and receiving messages docs

README.md, src/ActiveMQ.Net/Message.cs, test/ActiveMQ.Net.UnitTests/MessageSpec.cs
=> Support all amqp message payload types

README.md, src/ActiveMQ.Net/AnonymousProducer.cs, src/ActiveMQ.Net/AnonymousProducerConfiguration.cs, src/ActiveMQ.Net/AutoRecovering/AutoRecoveringAnonymousProducer.cs, src/ActiveMQ.Net/AutoRecovering/AutoRecoveringConnection.cs, src/ActiveMQ.Net/Builders/AnonymousProducerBuilder.cs, src/ActiveMQ.Net/Connection.cs, src/ActiveMQ.Net/ConnectionExtensions.cs, src/ActiveMQ.Net/Header.cs, src/ActiveMQ.Net/IBaseProducerConfiguration.cs, src/ActiveMQ.Net/IConnection.cs, src/ActiveMQ.Net/Message.cs, src/ActiveMQ.Net/Producer.cs, src/ActiveMQ.Net/ProducerBase.cs, src/ActiveMQ.Net/ProducerConfiguration.cs, src/ActiveMQ.Net/Properties.cs, test/ActiveMQ.Net.IntegrationTests/AnonymousMessageProducerSpec.cs, test/ActiveMQ.Net.IntegrationTests/MessagePrioritySpec.cs, test/ActiveMQ.Net.IntegrationTests/MessageRoutingStrategiesSpec.cs, test/ActiveMQ.Net.UnitTests/ActiveMQNetSpec.cs, test/ActiveMQ.Net.UnitTests/CreateAnonymousProducerSpec.cs, test/ActiveMQ.Net.UnitTests/CreateProducerSpec.cs, test/ActiveMQ.Net.UnitTests/MessagePrioritySpec.cs
=> Message priority support

ActiveMQ.Net.sln.DotSettings, README.md, src/ActiveMQ.Net/AnonymousProducerConfiguration.cs, src/ActiveMQ.Net/DurabilityMode.cs, src/ActiveMQ.Net/Header.cs, src/ActiveMQ.Net/IBaseProducerConfiguration.cs, src/ActiveMQ.Net/Message.cs, src/ActiveMQ.Net/ProducerBase.cs, src/ActiveMQ.Net/ProducerConfiguration.cs, test/ActiveMQ.Net.UnitTests/MessageDurabilityModeSpec.cs, test/ActiveMQ.Net.UnitTests/MessageSpec.cs
=> Message durability mode support

src/ActiveMQ.Net/Message.cs, test/ActiveMQ.Net.IntegrationTests/MessageGroupingSpec.cs, test/ActiveMQ.Net.UnitTests/MessageSpec.cs
=> Message Groups

src/ActiveMQ.Net/Header.cs, src/ActiveMQ.Net/Message.cs, test/ActiveMQ.Net.IntegrationTests/MessageExpirySpec.cs, test/ActiveMQ.Net.UnitTests/MessageSpec.cs
=> Message Expiry

src/ActiveMQ.Net/Builders/ConsumerBuilder.cs, src/ActiveMQ.Net/Builders/FilterExpression.cs, src/ActiveMQ.Net/ConsumerConfiguration.cs, test/ActiveMQ.Net.IntegrationTests/ActiveMQNetIntegrationSpec.cs, test/ActiveMQ.Net.IntegrationTests/FilterExpressionsSpec.cs, test/ActiveMQ.Net.TestUtils/DateTimeExtensions.cs
=> Filter Expressions

src/ActiveMQ.Net/Builders/ConsumerBuilder.cs, src/ActiveMQ.Net/Builders/NoLocalFilter.cs, src/ActiveMQ.Net/ConsumerConfiguration.cs, test/ActiveMQ.Net.IntegrationTests/NoLocalFilterSpec.cs, test/ActiveMQ.Net.UnitTests/NoLocalFilterSpec.cs
=> NoLocal filter

README.md, src/ActiveMQ.Net/AnonymousProducer.cs, src/ActiveMQ.Net/AutoRecovering/AutoRecoveringAnonymousProducer.cs, src/ActiveMQ.Net/AutoRecovering/AutoRecoveringConsumer.cs, src/ActiveMQ.Net/AutoRecovering/AutoRecoveringProducer.cs, src/ActiveMQ.Net/Builders/ConsumerBuilder.cs, src/ActiveMQ.Net/Builders/ProducerBuilder.cs, src/ActiveMQ.Net/Builders/TransactionCoordinatorBuilder.cs, src/ActiveMQ.Net/Connection.cs, src/ActiveMQ.Net/Consumer.cs, src/ActiveMQ.Net/ConsumerExtensions.cs, src/ActiveMQ.Net/Exceptions/CreateTransactionCoordinatorException.cs, src/ActiveMQ.Net/Exceptions/TransactionException.cs, src/ActiveMQ.Net/IAnonymousProducer.cs, src/ActiveMQ.Net/IConsumer.cs, src/ActiveMQ.Net/IProducer.cs, src/ActiveMQ.Net/InternalUtilities/TaskExtensions.cs, src/ActiveMQ.Net/MessageOutcomes.cs, src/ActiveMQ.Net/Producer.cs, src/ActiveMQ.Net/ProducerBase.cs, src/ActiveMQ.Net/ProducerExtensions.cs, src/ActiveMQ.Net/Transactions/Transaction.cs, src/ActiveMQ.Net/Transactions/TransactionCoordinator.cs, src/ActiveMQ.Net/Transactions/TransactionsManager.cs, test/ActiveMQ.Net.IntegrationTests/FilterExpressionsSpec.cs, test/ActiveMQ.Net.IntegrationTests/ScheduledDeliverySpec.cs, test/ActiveMQ.Net.IntegrationTests/TransactionsSpec.cs, test/ActiveMQ.Net.UnitTests/AutoRecovering/AutoRecoveringConsumerSpec.cs, test/ActiveMQ.Net.UnitTests/ConsumerMessageAcknowledgementSpec.cs
=> Transactions

src/ActiveMQ.Artemis.Client/AnonymousProducerConfiguration.cs, src/ActiveMQ.Artemis.Client/IBaseProducerConfiguration.cs, src/ActiveMQ.Artemis.Client/Message.cs, src/ActiveMQ.Artemis.Client/MessageIdPolicy/DisableMessageIdPolicy.cs, src/ActiveMQ.Artemis.Client/MessageIdPolicy/GuidMessageIdPolicy.cs, src/ActiveMQ.Artemis.Client/MessageIdPolicy/IMessageIdPolicy.cs, src/ActiveMQ.Artemis.Client/MessageIdPolicy/MessageIdPolicyFactory.cs, src/ActiveMQ.Artemis.Client/MessageIdPolicy/StringGuidMessageIdPolicy.cs, src/ActiveMQ.Artemis.Client/ProducerBase.cs, src/ActiveMQ.Artemis.Client/ProducerConfiguration.cs, src/ActiveMQ.Artemis.Client/Properties.cs, test/ActiveMQ.Artemis.Client.IntegrationTests/MessageIdPolicySpec.cs
=> Message Id policy

README.md
=> Add docs regarding connection auto-recovery

src/ActiveMQ.Artemis.Client/AutoRecovering/AutoRecoveringConsumer.cs, src/ActiveMQ.Artemis.Client/Consumer.cs, src/ActiveMQ.Artemis.Client/IConsumer.cs, test/ActiveMQ.Artemis.Client.IntegrationTests/MessageAcknowledgementSpec.cs, test/ActiveMQ.Artemis.Client.UnitTests/AutoRecovering/AutoRecoveringConsumerSpec.cs, test/ActiveMQ.Artemis.Client.UnitTests/ConsumerMessageAcknowledgementSpec.cs
=> Test message acknowledgment

src/ActiveMQ.Artemis.Client/Builders/AnonymousProducerBuilder.cs, src/ActiveMQ.Artemis.Client/Builders/ConnectionBuilder.cs, src/ActiveMQ.Artemis.Client/Builders/ConsumerBuilder.cs, src/ActiveMQ.Artemis.Client/Builders/ProducerBuilder.cs, src/ActiveMQ.Artemis.Client/Builders/SessionBuilder.cs, src/ActiveMQ.Artemis.Client/Builders/TransactionCoordinatorBuilder.cs, src/ActiveMQ.Artemis.Client/Endpoint.cs, src/ActiveMQ.Artemis.Client/Exceptions/ActiveMQArtemisClientException.cs, src/ActiveMQ.Artemis.Client/Exceptions/CreateConnectionException.cs, src/ActiveMQ.Artemis.Client/Exceptions/CreateConsumerException.cs, src/ActiveMQ.Artemis.Client/Exceptions/CreateEndpointException.cs, src/ActiveMQ.Artemis.Client/Exceptions/CreateProducerException.cs, src/ActiveMQ.Artemis.Client/Exceptions/CreateSessionException.cs, src/ActiveMQ.Artemis.Client/Exceptions/CreateTransactionCoordinatorException.cs, src/ActiveMQ.Artemis.Client/Exceptions/MessageSendException.cs, src/ActiveMQ.Artemis.Client/Exceptions/ProducerClosedException.cs, src/ActiveMQ.Artemis.Client/Exceptions/TransactionException.cs, src/ActiveMQ.Artemis.Client/ProducerBase.cs, src/ActiveMQ.Artemis.Client/Transactions/TransactionCoordinator.cs, test/ActiveMQ.Artemis.Client.UnitTests/CreateConsumerSpec.cs, test/ActiveMQ.Artemis.Client.UnitTests/EndpointSpec.cs
=> Reorganize exceptions hierarchy

src/ActiveMQ.Artemis.Client/AnonymousProducerConfiguration.cs, src/ActiveMQ.Artemis.Client/AutoRecovering/AutoRecoveringConnection.cs, src/ActiveMQ.Artemis.Client/Builders/ConnectionBuilder.cs, src/ActiveMQ.Artemis.Client/Builders/ProducerBuilder.cs, src/ActiveMQ.Artemis.Client/Connection.cs, src/ActiveMQ.Artemis.Client/ConnectionFactory.cs, src/ActiveMQ.Artemis.Client/Consumer.cs, src/ActiveMQ.Artemis.Client/Producer.cs, src/ActiveMQ.Artemis.Client/ProducerBase.cs, src/ActiveMQ.Artemis.Client/ProducerConfiguration.cs, test/ActiveMQ.Artemis.Client.IntegrationTests/ActiveMQNetIntegrationSpec.cs, test/ActiveMQ.Artemis.Client.UnitTests/ActiveMQNetSpec.cs, test/ActiveMQ.Artemis.Client.UnitTests/ConnectionFactorySpec.cs, test/ActiveMQ.Artemis.Client.UnitTests/MessageIdPolicySpec.cs
=> Add option to set message id policy globally on connection factory level

test/ActiveMQ.Artemis.Client.IntegrationTests/ScheduledDeliverySpec.cs, test/ActiveMQ.Artemis.Client.UnitTests/ConsumerReceiveMessageSpec.cs
=> Fix non deterministic test

test/ActiveMQ.Artemis.Client.IntegrationTests/TransactionsSpec.cs
=> Test scenario when transacted and non-transacted messages are sent alternately

src/ActiveMQ.Artemis.Client/AnonymousProducer.cs, src/ActiveMQ.Artemis.Client/AutoRecovering/AutoRecoveringAnonymousProducer.cs, src/ActiveMQ.Artemis.Client/AutoRecovering/AutoRecoveringConnection.cs, src/ActiveMQ.Artemis.Client/AutoRecovering/AutoRecoveringConsumer.cs, src/ActiveMQ.Artemis.Client/AutoRecovering/AutoRecoveringProducer.cs, src/ActiveMQ.Artemis.Client/AutoRecovering/AutoRecoveringProducerBase.cs, src/ActiveMQ.Artemis.Client/AutoRecovering/IRecoverable.cs, src/ActiveMQ.Artemis.Client/Builders/ProducerBuilder.cs, src/ActiveMQ.Artemis.Client/Consumer.cs, src/ActiveMQ.Artemis.Client/Exceptions/ConsumerClosedException.cs, src/ActiveMQ.Artemis.Client/IAnonymousProducer.cs, src/ActiveMQ.Artemis.Client/IProducer.cs, src/ActiveMQ.Artemis.Client/Producer.cs, test/ActiveMQ.Artemis.Client.UnitTests/AutoRecovering/AutoRecoveringConsumerSpec.cs, test/ActiveMQ.Artemis.Client.UnitTests/AutoRecovering/AutoRecoveringProducerSpec.cs
=> SendAsync should throw immediately after recovery policy gives up

website/docusaurus.config.js
=> Fix docs edit url

.github/workflows/dotnetcore.yml, docker-compose.yml, test/artemis/docker-compose.yml, test/artemis/etc-override/broker-00.xml
=> Run Artemis for tests with custom configuration

src/ActiveMQ.Artemis.Client/Message.cs, src/ActiveMQ.Artemis.Client/Properties.cs, test/ActiveMQ.Artemis.Client.UnitTests/MessageSpec.cs
=> CorrelationId support

src/ActiveMQ.Artemis.Client/ActiveMQ.Artemis.Client.csproj, src/ActiveMQ.Artemis.Client/ApplicationProperties.cs, src/ActiveMQ.Artemis.Client/AutoRecovering/AutoRecoveringConnection.cs, src/ActiveMQ.Artemis.Client/Builders/RpcClientBuilder.cs, src/ActiveMQ.Artemis.Client/Connection.cs, src/ActiveMQ.Artemis.Client/Exceptions/CreateRpcClientException.cs, src/ActiveMQ.Artemis.Client/Exceptions/CreateTopologyManagerException.cs, src/ActiveMQ.Artemis.Client/IConnection.cs, src/ActiveMQ.Artemis.Client/ITopologyManager.cs, src/ActiveMQ.Artemis.Client/InternalUtilities/DisposeUtil.cs, src/ActiveMQ.Artemis.Client/InternalUtilities/TaskUtil.cs, src/ActiveMQ.Artemis.Client/Management/RequestSerializer.cs, src/ActiveMQ.Artemis.Client/Management/RpcClient.cs, src/ActiveMQ.Artemis.Client/Management/TopologyManager.cs, src/ActiveMQ.Artemis.Client/ProducerBase.cs, src/ActiveMQ.Artemis.Client/Properties.cs, src/ActiveMQ.Artemis.Client/QueueConfiguration.cs, src/ActiveMQ.Artemis.Client/Transactions/TransactionCoordinator.cs, test/ActiveMQ.Artemis.Client.IntegrationTests/TopologyManagementSpec.cs, test/ActiveMQ.Artemis.Client.UnitTests/AutoRecovering/AutoRecoveringConnectionSpec.cs, test/ActiveMQ.Artemis.Client.UnitTests/AutoRecovering/AutoRecoveringConsumerSpec.cs, test/ActiveMQ.Artemis.Client.UnitTests/AutoRecovering/AutoRecoveringProducerSpec.cs
=> Topology management support

src/ActiveMQ.Artemis.Client/AutoRecovering/AutoRecoveringAnonymousProducer.cs, src/ActiveMQ.Artemis.Client/AutoRecovering/AutoRecoveringConnection.cs, src/ActiveMQ.Artemis.Client/AutoRecovering/AutoRecoveringConsumer.cs, src/ActiveMQ.Artemis.Client/AutoRecovering/AutoRecoveringProducer.cs, src/ActiveMQ.Artemis.Client/AutoRecovering/AutoRecoveringProducerBase.cs, src/ActiveMQ.Artemis.Client/AutoRecovering/IRecoverable.cs, src/ActiveMQ.Artemis.Client/Connection.cs, src/ActiveMQ.Artemis.Client/Consumer.cs, src/ActiveMQ.Artemis.Client/Exceptions/ConnectionClosedException.cs, src/ActiveMQ.Artemis.Client/Exceptions/ProducerClosedException.cs, src/ActiveMQ.Artemis.Client/InternalUtilities/ActionUtil.cs, src/ActiveMQ.Artemis.Client/Management/RpcClient.cs, src/ActiveMQ.Artemis.Client/ProducerBase.cs, test/ActiveMQ.Artemis.Client.UnitTests/ActiveMQNetSpec.cs, test/ActiveMQ.Artemis.Client.UnitTests/AutoRecovering/AutoRecoveringConnectionSpec.cs, test/ActiveMQ.Artemis.Client.UnitTests/ClosedConnectionSpec.cs, test/ActiveMQ.Artemis.Client.UnitTests/ClosedConsumerSpec.cs, test/ActiveMQ.Artemis.Client.UnitTests/ClosedProducerSpec.cs, test/ActiveMQ.Artemis.Client.UnitTests/Utils/EndpointUtil.cs
=> Handle disposed/closed resources

src/ActiveMQ.Artemis.Client/Management/RpcClient.cs
=> Fix race condition in RpcClient

src/ActiveMQ.Artemis.Client/AutoRecovering/AutoRecoveringAnonymousProducer.cs, src/ActiveMQ.Artemis.Client/AutoRecovering/AutoRecoveringConnection.cs, src/ActiveMQ.Artemis.Client/Connection.cs, src/ActiveMQ.Artemis.Client/ConnectionExtensions.cs, src/ActiveMQ.Artemis.Client/IConnection.cs, src/ActiveMQ.Artemis.Client/ITopologyManager.cs, src/ActiveMQ.Artemis.Client/Management/TopologyManager.cs, test/ActiveMQ.Artemis.Client.IntegrationTests/AnonymousMessageProducerSpec.cs, test/ActiveMQ.Artemis.Client.IntegrationTests/MessageAcknowledgementSpec.cs, test/ActiveMQ.Artemis.Client.IntegrationTests/MessageCreationTimeSpec.cs, test/ActiveMQ.Artemis.Client.IntegrationTests/MessagePrioritySpec.cs, test/ActiveMQ.Artemis.Client.IntegrationTests/TopologyManagementSpec.cs, test/ActiveMQ.Artemis.Client.IntegrationTests/TransactionsSpec.cs, test/ActiveMQ.Artemis.Client.UnitTests/ClosedConnectionSpec.cs, test/ActiveMQ.Artemis.Client.UnitTests/CreateAnonymousProducerSpec.cs
=> Add missing async postfixes

test/ActiveMQ.Artemis.Client.IntegrationTests/AddressModelSpec.cs, test/artemis/etc-override/broker-00.xml
=> Refactor Address Model tests to use topology management

src/ActiveMQ.Artemis.Client/Builders/ConsumerBuilder.cs, src/ActiveMQ.Artemis.Client/ConnectionExtensions.cs, src/ActiveMQ.Artemis.Client/Consumer.cs, src/ActiveMQ.Artemis.Client/ConsumerConfiguration.cs, test/ActiveMQ.Artemis.Client.UnitTests/CreateConsumerSpec.cs
=> Remove advanced queue configuration during consumer creation

test/ActiveMQ.Artemis.Client.UnitTests/Utils/EndpointUtil.cs
=> Get free port for tests instead of choosing it randomly

.github/workflows/release.yml, src/ActiveMQ.Artemis.Client/ActiveMQ.Artemis.Client.csproj
=> Create release to NuGet workflow

README.md, benchmark/PingPong/Program.cs, src/ActiveMQ.Artemis.Client/ITopologyManager.cs, src/ActiveMQ.Artemis.Client/Management/RequestSerializer.cs, src/ActiveMQ.Artemis.Client/Management/TopologyManager.cs, test/ActiveMQ.Artemis.Client.IntegrationTests/DeclareAddressSpec.cs, test/ActiveMQ.Artemis.Client.IntegrationTests/TopologyManagement/CreateAddressSpec.cs, test/ActiveMQ.Artemis.Client.IntegrationTests/TopologyManagement/CreateQueueSpec.cs, test/ActiveMQ.Artemis.Client.IntegrationTests/TopologyManagement/DeclareAddressSpec.cs, test/ActiveMQ.Artemis.Client.IntegrationTests/TopologyManagement/QueryingResourcesSpec.cs
=> Idempotent address creation

src/ActiveMQ.Artemis.Client/AutoRecovering/AutoRecoveringAnonymousProducer.cs, src/ActiveMQ.Artemis.Client/AutoRecovering/AutoRecoveringConsumer.cs, src/ActiveMQ.Artemis.Client/AutoRecovering/AutoRecoveringProducer.cs
=> Fix bug with access to disposed resource after resource recovered

README.md, src/ActiveMQ.Artemis.Client/ITopologyManager.cs, src/ActiveMQ.Artemis.Client/Management/TopologyManager.cs, test/ActiveMQ.Artemis.Client.IntegrationTests/ActiveMQNetIntegrationSpec.cs, test/ActiveMQ.Artemis.Client.IntegrationTests/TopologyManagement/DeleteQueueSpec.cs
=> Support queue removal

src/ActiveMQ.Artemis.Client/ITopologyManager.cs, src/ActiveMQ.Artemis.Client/Management/TopologyManager.cs, test/ActiveMQ.Artemis.Client.IntegrationTests/TopologyManagement/DeleteQueueSpec.cs
=> Rename DeleteQueue -> DeleteQueueAsync

README.md, src/ActiveMQ.Artemis.Client/ITopologyManager.cs, src/ActiveMQ.Artemis.Client/Management/TopologyManager.cs, test/ActiveMQ.Artemis.Client.IntegrationTests/TopologyManagement/DeleteAddressSpec.cs
=> Delete address support

test/ActiveMQ.Artemis.Client.IntegrationTests/AddressModelSpec.cs, test/ActiveMQ.Artemis.Client.IntegrationTests/AnonymousMessageProducerSpec.cs, test/ActiveMQ.Artemis.Client.IntegrationTests/ConsumerCreditSpec.cs, test/ActiveMQ.Artemis.Client.IntegrationTests/FilterExpressionsSpec.cs, test/ActiveMQ.Artemis.Client.IntegrationTests/MessageCreationTimeSpec.cs, test/ActiveMQ.Artemis.Client.IntegrationTests/MessageExpirySpec.cs, test/ActiveMQ.Artemis.Client.IntegrationTests/MessageGroupingSpec.cs, test/ActiveMQ.Artemis.Client.IntegrationTests/MessagePrioritySpec.cs, test/ActiveMQ.Artemis.Client.IntegrationTests/MessageRoutingStrategiesSpec.cs, test/ActiveMQ.Artemis.Client.IntegrationTests/NoLocalFilterSpec.cs, test/ActiveMQ.Artemis.Client.IntegrationTests/ScheduledDeliverySpec.cs
This is an attempt to stabilize integration tests that sometimes fail.
=> Stabilize integration tests

src/ActiveMQ.Artemis.Client/Management/RequestSerializer.cs, src/ActiveMQ.Artemis.Client/QueueConfiguration.cs, test/ActiveMQ.Artemis.Client.IntegrationTests/TopologyManagement/CreateQueueSpec.cs
=> Create queue with filter expression

README.md, src/ActiveMQ.Artemis.Client/ITopologyManager.cs, src/ActiveMQ.Artemis.Client/Management/RequestSerializer.cs, src/ActiveMQ.Artemis.Client/Management/TopologyManager.cs, test/ActiveMQ.Artemis.Client.IntegrationTests/AddressModelSpec.cs, test/ActiveMQ.Artemis.Client.IntegrationTests/TopologyManagement/DeclareAddressSpec.cs, test/ActiveMQ.Artemis.Client.IntegrationTests/TopologyManagement/DeclareQueueSpec.cs, test/ActiveMQ.Artemis.Client.UnitTests/AutoRecovering/AutoRecoveringConsumerSpec.cs
=> Idempotent queue creation

README.md, src/ActiveMQ.Artemis.Client/Management/TopologyManager.cs
=> Argument null exception when queue declared without filter expression

src/ActiveMQ.Artemis.Client/InternalUtilities/DisposeUtil.cs, test/ActiveMQ.Artemis.Client.UnitTests/AutoRecovering/AutoRecoveringConnectionSpec.cs
=> Dispose util should be internal

docs/consumer-credit.md
=> Consumer credit docs

test/ActiveMQ.Artemis.Client.IntegrationTests/TopologyManagement/DeclareQueueSpec.cs, test/artemis/docker-compose.yml
=> Bump artemis version to 2.14.0

src/ActiveMQ.Artemis.Client/Message.cs, test/ActiveMQ.Artemis.Client.IntegrationTests/MessageSubjectSpec.cs
=> Add support for subject field

src/ActiveMQ.Artemis.Client/Message.cs, test/ActiveMQ.Artemis.Client.IntegrationTests/MessageReplyToSpec.cs
=> Support for reply-to field

src/ActiveMQ.Artemis.Client/Message.cs, test/ActiveMQ.Artemis.Client.IntegrationTests/MessageUserIdSpec.cs
=> Support for user-id

src/ActiveMQ.Artemis.Client/Header.cs, src/ActiveMQ.Artemis.Client/Message.cs, test/ActiveMQ.Artemis.Client.IntegrationTests/MessageDeliveryCountSpec.cs
=> Support for message delivery count

src/ActiveMQ.Artemis.Client/Message.cs, test/ActiveMQ.Artemis.Client.IntegrationTests/MessageToSpec.cs
=> Support for To field

src/ActiveMQ.Artemis.Client/ApplicationProperties.cs, test/ActiveMQ.Artemis.Client.UnitTests/MessageSpec.cs
=> Add TryGetValue<T> and ContainsKey methods to ApplicationProperties API

src/ActiveMQ.Artemis.Client/ActiveMQ.Artemis.Client.csproj
=> Use Source Link

test/artemis/docker-compose.yml
=> Bump up Artemis version to 2.16

src/ActiveMQ.Artemis.Client/Configuration/QueueConfiguration.cs, src/ActiveMQ.Artemis.Client/Management/RequestSerializer.cs, test/ActiveMQ.Artemis.Client.IntegrationTests/TopologyManagement/AutoDeletingQueuesSpec.cs, test/ActiveMQ.Artemis.Client.TestUtils/Retry.cs, test/artemis/etc-override/broker-00.xml
=> Add auto-delete queues support

src/ActiveMQ.Artemis.Client/ActiveMQ.Artemis.Client.csproj, test/ActiveMQ.Artemis.Client.IntegrationTests/TopologyManagement/AutoDeletingQueuesSpec.cs
=> Update AMQPNetLite to 2.4.2 

src/ActiveMQ.Artemis.Client/Extensions/RoutingTypeExtensions.cs, test/ActiveMQ.Artemis.Client.UnitTests/ProducerSendMessageSpec.cs
Changed RoutingAnnotation type to sbyte.
Tested on artemis-2.6.3 and artemis-2.17.0.
Addresses #259 .
=> Fix Fail sending message to artemis-2.6.3 #259

src/ActiveMQ.Artemis.Client/ActiveMQ.Artemis.Client.csproj, src/ActiveMQ.Artemis.Client/ProducerBase.cs, test/ActiveMQ.Artemis.Client.IntegrationTests/AddressBlockPolicySpec.cs, test/artemis/broker.xml
It requires the release of https://github.com/Azure/amqpnetlite/pull/466. 
This closes #277.
=> Cancel inflight messages after send cancelled

samples/ArtemisNetClient.Examples.AspNetCore/Startup.cs, src/ArtemisNetClient/AutoRecovering/AutoRecoveringConnection.cs
=> Fix auto-recovery issue

src/ArtemisNetClient.Extensions.DependencyInjection/ActiveMqConsumer.cs
=> Break consumer pooling loop when connection was marked as unrecoverable

.github/workflows/build.yml, .github/workflows/release.yml, benchmark/PingPong/PingPong.csproj, samples/ArtemisNetClient.Examples.AspNetCore/ArtemisNetClient.Examples.AspNetCore.csproj, samples/ArtemisNetClient.Examples.LeaderElection/ArtemisNetClient.Examples.LeaderElection.csproj, src/ArtemisNetClient.Extensions.App.Metrics/ArtemisNetClient.Extensions.App.Metrics.csproj, src/ArtemisNetClient.Extensions.DependencyInjection/ArtemisNetClient.Extensions.DependencyInjection.csproj, src/ArtemisNetClient.Extensions.Hosting/ArtemisNetClient.Extensions.Hosting.csproj, src/ArtemisNetClient.Extensions.LeaderElection/ArtemisNetClient.Extensions.LeaderElection.csproj, src/ArtemisNetClient/ArtemisNetClient.csproj, test/ArtemisNetClient.Extensions.App.Metrics.IntegrationTests/ArtemisNetClient.Extensions.App.Metrics.IntegrationTests.csproj, test/ArtemisNetClient.Extensions.App.Metrics.IntegrationTests/ProcessingMessageMetricsSpec.cs, test/ArtemisNetClient.Extensions.App.Metrics.IntegrationTests/TestFixture.cs, test/ArtemisNetClient.Extensions.IntegrationTests/ArtemisNetClient.Extensions.IntegrationTests.csproj, test/ArtemisNetClient.Extensions.IntegrationTests/ConsumerSpec.cs, test/ArtemisNetClient.Extensions.IntegrationTests/Observables/ReceiveObserverSpec.cs, test/ArtemisNetClient.Extensions.IntegrationTests/RegisterConsumerSpec.cs, test/ArtemisNetClient.Extensions.IntegrationTests/TestFixture.cs, test/ArtemisNetClient.Extensions.LeaderElection.IntegrationTests/ArtemisNetClient.Extensions.LeaderElection.IntegrationTests.csproj, test/ArtemisNetClient.IntegrationTests/ArtemisNetClient.IntegrationTests.csproj, test/ArtemisNetClient.IntegrationTests/TopologyManagement/DeleteQueueSpec.cs, test/ArtemisNetClient.TestUtils/ArtemisNetClient.TestUtils.csproj, test/ArtemisNetClient.UnitTests/ArtemisNetClient.UnitTests.csproj, test/ArtemisNetClient.UnitTests/MessageSpec.cs
=> Bump up dotnet version to 6.0

samples/ArtemisNetClient.Examples.AspNetCore/Startup.cs, src/ArtemisNetClient.Extensions.DependencyInjection/ActiveMqArtemisClientDependencyInjectionExtensions.cs, src/ArtemisNetClient.Extensions.DependencyInjection/Options/ActiveMqOptions.cs
It closes #311 and answers #305.
=> Add option to configure connection via DI API

README.md, src/ArtemisNetClient.Extensions.DependencyInjection/ActiveMqArtemisClientDependencyInjectionExtensions.cs, src/ArtemisNetClient/Builders/ConsumerBuilder.cs, src/ArtemisNetClient/Configuration/ConsumerConfiguration.cs, src/ArtemisNetClient/Constants/TerminusDurability.cs, src/ArtemisNetClient/Consumer.cs, test/ArtemisNetClient.Extensions.IntegrationTests/ConsumerSpec.cs, test/ArtemisNetClient.IntegrationTests/SharedConsumerSpec.cs, test/ArtemisNetClient.IntegrationTests/SharedDurableConsumerSpec.cs, test/artemis/broker.xml, test/artemis/docker-compose.yml
=> Support shared durable consumer

README.md, test/ArtemisNetClient.IntegrationTests/TopologyManagement/DeleteQueueSpec.cs, test/artemis/Dockerfile, test/artemis/docker-compose.yml
=> Bump Artemis to 2.20.0

README.md, test/artemis/Dockerfile, test/artemis/docker-compose.yml
=> Bump Artemis to 2.21.0

README.md, test/artemis/Dockerfile, test/artemis/docker-compose.yml
=> Bump Artemis to 2.22.0

src/ArtemisNetClient.Extensions.App.Metrics/ArtemisNetClient.Extensions.App.Metrics.csproj, src/ArtemisNetClient.Extensions.DependencyInjection/ArtemisNetClient.Extensions.DependencyInjection.csproj, src/ArtemisNetClient.Extensions.Hosting/ArtemisNetClient.Extensions.Hosting.csproj, src/ArtemisNetClient.Extensions.LeaderElection/ArtemisNetClient.Extensions.LeaderElection.csproj, src/ArtemisNetClient.Testing/ArtemisNetClient.Testing.csproj, src/ArtemisNetClient/ArtemisNetClient.csproj
=> Generates an XML documentation for library

src/ArtemisNetClient/ArtemisNetClient.csproj
=> Bump AmqpNetLite to the version 2.4.4

README.md, test/artemis/Dockerfile, test/artemis/docker-compose.yml
=> Bump Artemis to 2.23.0

README.md, docs/online-resources.md
https://blog.jeroenmaes.eu/2021/12/run-activemq-artemis-in-docker-for-local-development/
=> Add link to article about running Artemis in Docker for local development

README.md, test/artemis/Dockerfile, test/artemis/docker-compose.yml
=> Bump Artemis to 2.23.1

docs/connection-lifecycle.md, src/ArtemisNetClient/IConnection.cs, test/ArtemisNetClient.UnitTests/AutoRecovering/AutoRecoveringConnectionSpec.cs, test/ArtemisNetClient.UnitTests/ConnectionSpec.cs, test/ArtemisNetClient.UnitTests/Utils/TestHandler.cs, website/sidebars.js
=> Add missing tests and docs for ConnectionClosed event

README.md
=> Add docs regarding building and running tests

test/artemis/Dockerfile, test/artemis/docker-compose.yml
=> Bump artemis to 2.24.0

src/ArtemisNetClient/AutoRecovering/AutoRecoveringConnection.cs, src/ArtemisNetClient/Builders/ConnectionBuilder.cs, src/ArtemisNetClient/ConnectionFactory.cs, test/ArtemisNetClient.UnitTests/ConnectionFactorySpec.cs
=> Add option to override client-id

docs/transactions.md, website/sidebars.js
=> Add transactions docs

src/ArtemisNetClient/ArtemisNetClient.csproj
=> Update AMQPNetLite to 2.4.5

README.md, test/artemis/Dockerfile, test/artemis/docker-compose.yml
=> Bump Artemis to 2.25.0

README.md, test/artemis/Dockerfile, test/artemis/docker-compose.yml
=> Bump Artemis to 2.26.0

src/ArtemisNetClient.Extensions.DependencyInjection/Options/QueueOptions.cs, src/ArtemisNetClient/Configuration/QueueConfiguration.cs, src/ArtemisNetClient/Management/RequestSerializer.cs, test/ArtemisNetClient.IntegrationTests/TopologyManagement/CreateQueueSpec.cs
=> Add Last-Value Queues support

src/ArtemisNetClient.Extensions.DependencyInjection/ActiveMqArtemisClientDependencyInjectionExtensions.cs
=> Use LastValueKey in ArtemisNetClient.Extensions

src/ArtemisNetClient.Extensions.DependencyInjection/ActiveMqArtemisClientDependencyInjectionExtensions.cs, src/ArtemisNetClient.Extensions.DependencyInjection/Options/QueueOptions.cs, src/ArtemisNetClient/Configuration/QueueConfiguration.cs, src/ArtemisNetClient/Management/RequestSerializer.cs, test/ArtemisNetClient.IntegrationTests/TopologyManagement/CreateQueueSpec.cs
=> Add non-destructive queues support

README.md, test/artemis/Dockerfile, test/artemis/docker-compose.yml
=> Bump Artemis to 2.27.0

src/ArtemisNetClient.Extensions.DependencyInjection/ActiveMqArtemisClientDependencyInjectionExtensions.cs, src/ArtemisNetClient.Extensions.DependencyInjection/ActiveMqTopologyManager.cs, src/ArtemisNetClient.Extensions.DependencyInjection/Options/ActiveMqOptions.cs, test/ArtemisNetClient.Extensions.IntegrationTests/ConfigureTopologySpec.cs
It closes #399 and answers #398.
=> Add option to configure broker topology in DI extensions

src/ArtemisNetClient/Message/Message.cs, test/ArtemisNetClient.UnitTests/MessageSpec.cs
=> Add support for content-type field

.github/workflows/release.yml, ActiveMQ.Artemis.Client.sln, README.md, src/ArtemisNetClient.Extensions.CloudEvents/ArtemisNetClient.Extensions.CloudEvents.csproj, src/ArtemisNetClient.Extensions.CloudEvents/CloudEventsExtensions.cs, test/ArtemisNetClient.Extensions.CloudEvents.UnitTests/ArtemisNetClient.Extensions.CloudEvents.UnitTests.csproj, test/ArtemisNetClient.Extensions.CloudEvents.UnitTests/CloudEventsSpec.cs
=> Add CloudEvents support

README.md, test/artemis/Dockerfile, test/artemis/docker-compose.yml
=> Bump Artemis to 2.27.1

src/ArtemisNetClient.Extensions.DependencyInjection/ActiveMqClient.cs, test/ArtemisNetClient.Extensions.IntegrationTests/ConfigureTopologySpec.cs
=> Invoke ConfigureTopology before message producers are created

src/ArtemisNetClient.Extensions.DependencyInjection/ActiveMqArtemisClientDependencyInjectionExtensions.cs, src/ArtemisNetClient.Extensions.DependencyInjection/ConnectionProvider.cs, src/ArtemisNetClient.Extensions.DependencyInjection/InternalUtils/AsyncValueLazy.cs, test/ArtemisNetClient.Extensions.IntegrationTests/ConnectionProviderSpec.cs, test/ArtemisNetClient.Extensions.IntegrationTests/TestFixture.cs
=> Adjust ConnectionProvider public API 

website/docusaurus.config.js, website/package.json, website/yarn.lock
=> Bump Docusaurus to 2.2.0

website/docusaurus.config.js
=> Update algolia api key

website/docusaurus.config.js
=> Disable contextualSearch

README.md, test/artemis/Dockerfile, test/artemis/docker-compose.yml
=> Bump Artemis to 2.29.0

src/ArtemisNetClient/Transactions/TransactionCoordinator.cs
=> Do not throw exception when transaction callback already completed

src/ArtemisNetClient.Testing/Listener/ContainerHost.cs, src/ArtemisNetClient.Testing/Listener/Extensions.cs, src/ArtemisNetClient.Testing/Listener/LinkCollection.cs, src/ArtemisNetClient.Testing/SharedMessageSource.cs, src/ArtemisNetClient.Testing/TestKit.cs, src/ArtemisNetClient.Testing/TestLinkProcessor.cs, src/ArtemisNetClient.Testing/Utils/ArtemisBucketHelper.cs, test/ArtemisNetClient.Testing.UnitTests/SendMessageSpec.cs
=> Test kit multiple shared consumers

README.md, test/artemis/Dockerfile, test/artemis/docker-compose.yml
=> Update Artemis to 2.30.0

.github/workflows/build.yml, src/ArtemisNetClient/ArtemisNetClient.csproj, src/ArtemisNetClient/Builders/ConnectionBuilder.cs, src/ArtemisNetClient/Configuration/Endpoint.cs, src/ArtemisNetClient/Configuration/Scheme.cs, test/ArtemisNetClient.IntegrationTests/WebSocketsSpec.cs, test/ArtemisNetClient.UnitTests/EndpointSpec.cs, test/artemis/Dockerfile, test/artemis/broker.xml, test/artemis/docker-compose.yml
=> Support for AMQP protocol over WebSockets

src/ArtemisNetClient.Testing/TestLinkProcessor.cs
=> Fix NRE when FilterSet is null

src/ArtemisNetClient.Testing/Listener/Extensions.cs, src/ArtemisNetClient.Testing/TestLinkProcessor.cs, src/ArtemisNetClient.Testing/Utils/ReflectionUtils.cs, test/ArtemisNetClient.Testing.UnitTests/SendMessageSpec.cs
=> Fix NRE when multiple transactional consumers attached to the same address

src/ArtemisNetClient.Testing/TestLinkProcessor.cs, test/ArtemisNetClient.Testing.UnitTests/ArtemisNetClient.Testing.UnitTests.csproj, test/ArtemisNetClient.Testing.UnitTests/FilterExpressionsSpec.cs
=> Fix message selector filtering in NMS.AMQP consumer

.github/workflows/build.yml, .github/workflows/release.yml, benchmark/PingPong/PingPong.csproj, samples/ArtemisNetClient.Examples.AspNetCore/ArtemisNetClient.Examples.AspNetCore.csproj, samples/ArtemisNetClient.Examples.LeaderElection/ArtemisNetClient.Examples.LeaderElection.csproj, samples/Testing/Application.Tests/Application.Tests.csproj, samples/Testing/Application/Application.csproj, src/ArtemisNetClient.Extensions.App.Metrics/ArtemisNetClient.Extensions.App.Metrics.csproj, src/ArtemisNetClient.Extensions.CloudEvents/ArtemisNetClient.Extensions.CloudEvents.csproj, src/ArtemisNetClient.Extensions.DependencyInjection/ArtemisNetClient.Extensions.DependencyInjection.csproj, src/ArtemisNetClient.Extensions.Hosting/ArtemisNetClient.Extensions.Hosting.csproj, src/ArtemisNetClient.Extensions.LeaderElection/ArtemisNetClient.Extensions.LeaderElection.csproj, src/ArtemisNetClient.Testing/ArtemisNetClient.Testing.csproj, src/ArtemisNetClient/ArtemisNetClient.csproj, src/Directory.Build.props, test/ArtemisNetClient.Extensions.App.Metrics.IntegrationTests/ArtemisNetClient.Extensions.App.Metrics.IntegrationTests.csproj, test/ArtemisNetClient.Extensions.App.Metrics.IntegrationTests/TestFixture.cs, test/ArtemisNetClient.Extensions.CloudEvents.UnitTests/ArtemisNetClient.Extensions.CloudEvents.UnitTests.csproj, test/ArtemisNetClient.Extensions.IntegrationTests/ArtemisNetClient.Extensions.IntegrationTests.csproj, test/ArtemisNetClient.Extensions.LeaderElection.IntegrationTests/ArtemisNetClient.Extensions.LeaderElection.IntegrationTests.csproj, test/ArtemisNetClient.IntegrationTests/ArtemisNetClient.IntegrationTests.csproj, test/ArtemisNetClient.TestUtils/ArtemisNetClient.TestUtils.csproj, test/ArtemisNetClient.Testing.UnitTests/ArtemisNetClient.Testing.UnitTests.csproj, test/ArtemisNetClient.UnitTests/ArtemisNetClient.UnitTests.csproj, test/Directory.Build.props
=> Bump to dotnet 8

src/ArtemisNetClient.Extensions.DependencyInjection/ActiveMqArtemisClientDependencyInjectionExtensions.cs, src/ArtemisNetClient/Builders/ConsumerBuilder.cs, test/ArtemisNetClient.UnitTests/CreateConsumerSpec.cs
=> Pass routing type when attaching consumer using FQQN

src/ArtemisNetClient/AutoRecovering/AutoRecoveringConnection.cs, src/ArtemisNetClient/Builders/ConnectionBuilder.cs, src/ArtemisNetClient/Configuration/TcpSettings.cs, src/ArtemisNetClient/ConnectionFactory.cs
=> Expose TCP keep alive settings

samples/ArtemisNetClient.Examples.AspNetCore/Startup.cs, src/ArtemisNetClient/Builders/ConnectionBuilder.cs
=> Fix keep alive settings

src/ArtemisNetClient/Message/Message.cs, test/ArtemisNetClient.UnitTests/MessageSpec.cs
=> Read Guid MessageId as string if possible

src/ArtemisNetClient/AutoRecovering/AutoRecoveringConnection.cs
=> Log connect attempt count properly

test/artemis/Dockerfile, test/artemis/docker-compose.yml
=> Bump Artemis to 2.34.0

src/ArtemisNetClient/Message/Message.cs, test/ArtemisNetClient.UnitTests/MessageSpec.cs
=> Support for content-encoding field
